# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "${SHOPIFY_API_KEY}"
name = "AI GEO & AEO Optimizer"
handle = "ai-geo-aeo-optimizer"
application_url = "https://magenta-piroshki-22a056.netlify.app"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "${SHOPIFY_DEV_STORE}"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://${HOST}/api/auth/callback",
  "https://magenta-piroshki-22a056.netlify.app/api/auth/callback",
  "https://magenta-piroshki-22a056.netlify.app/api/auth",
  "https://magenta-piroshki-22a056.netlify.app/auth/callback",
  "https://magenta-piroshki-22a056.netlify.app/",
  "https://magenta-piroshki-22a056.netlify.app"
]
use_legacy_install_flow = true

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/api/webhooks/products-update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions_update" ]
  uri = "/api/webhooks/app_subscriptions_update"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/api/webhooks/gdpr"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/api/webhooks/gdpr"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/api/webhooks/gdpr"

[pos]
embedded = false

